{"name": "Ошибка при получении заказа неавторизованным пользователем", "status": "passed", "start": 1706555518149, "stop": 1706555518622, "uuid": "de2e0f0e-ea3f-4e80-8eaa-1ab0103e7a45", "historyId": "5baaf3849fcbd18ae3901d4f3f63afcf", "testCaseId": "5baaf3849fcbd18ae3901d4f3f63afcf", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_user_without_authorisation_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-R8S2KV9"}, {"name": "thread", "value": "6472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}